---
title: "Toronto's Most Profitable Fire Hydrants"
author: "David Brait"
date: "Tuesday, February 23, 2016"
output: html_document
---

Expanding on my last post about Toronto's most expensive parking tickets, I decided to dive back into the city of Toronto's parking ticket data.  Through the years fire hydrants have been very profitable for the city.  In 2015, there were **x** issued for parking within 3 meters of a fire hydrant.  At $100 per ticket, that produced close to **x** in revenue for the city.  

Diving deeper into the data, there are specific fire hydrants that produce an inordinate amount of revenue for the city.  The most ticketed address in 2014 was 393 University Avenue, where 473 tickets alone were issued.  In other words, this fire hydrant averaged over a ticket a day and cost Toronto drivers **$47,300**.  393 University has been a consistent cash cow, bringing in **$55,700 in 2013**.

The 99 Atlantic Avenue spot saw 419 tickets issued in 2015, grossing $41,900 in revenue.  It seems to fluctuate year to year, with 

## 99 Atlantic Avenue

<iframe src="https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sca!4v1459021548161!6m8!1m7!1sX0OK39_7bJGnM06zg9JEeQ!2m2!1d43.63882940778376!2d-79.42074186786105!3f61.47514053371303!4f-8.382846273277451!5f0.7820865974627469" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

## 393 University Avenue

<iframe src="https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sca!4v1455652627436!6m8!1m7!1sBK4KPKn3h6N4FDeZGhrUgA!2m2!1d43.6539782753703!2d-79.38777639705907!3f78.41171713289268!4f-7.710372693569539!5f1.9587109090973311" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

There were several other high grossing hydrants in Toronto that were similarly ambigious.  Down the street at 361 University Avenue.  This hydrant also set back and semi camoflauged by the concrete and vegetation generated x in 2014, y, in 2013, and z in 2012.

# 361 University Avenue

<iframe src="https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sca!4v1455652940336!6m8!1m7!1shbtYT-UhvQ1GTVNVmLGW5g!2m2!1d43.65222091679838!2d-79.38701319822763!3f72.60574563179254!4f-8.072230771617356!5f1.9587109090973311" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

At 56 The Esplanade this hydrant is set back and can blend in with what is a busy street.  The address saw 180 tickets issued every year since 2013, brining in $18,000+ in revenue each year.

## 56 The Esplanade

<iframe src="https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sca!4v1455654497275!6m8!1m7!1sopulBUBlHmhh3TEFD0T3gQ!2m2!1d43.64683356988579!2d-79.37419983484568!3f4.738445161518996!4f-12.025359843131255!5f1.9587109090973311" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

592 Markham St is another one, off the street a signifant distance from where the car is parked.  Over 200 tickets were issued in 2015, for just over $20,000 in revenue.

## 592 Markham St

<iframe src="https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sca!4v1455653928162!6m8!1m7!1svaqjdYTzDfIh7_Y848MzOw!2m2!1d43.66391848655421!2d-79.41204901729137!3f221.67106089293168!4f-9.43902048433712!5f0.7820865974627469" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>



